/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnchorNavigation: typeof import('./src/components/AnchorNavigation.vue')['default']
    ApexChart: typeof import('./src/components/ApexChart.vue')['default']
    AppMenu: typeof import('./src/components/AppMenu/index.vue')['default']
    BBadge: typeof import('bootstrap-vue-next')['BBadge']
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BCol: typeof import('bootstrap-vue-next')['BCol']
    BCollapse: typeof import('bootstrap-vue-next')['BCollapse']
    BContainer: typeof import('bootstrap-vue-next')['BContainer']
    BDropdown: typeof import('bootstrap-vue-next')['BDropdown']
    BDropdownItem: typeof import('bootstrap-vue-next')['BDropdownItem']
    BForm: typeof import('bootstrap-vue-next')['BForm']
    BFormInput: typeof import('bootstrap-vue-next')['BFormInput']
    BFormRadio: typeof import('bootstrap-vue-next')['BFormRadio']
    BFormRadioGroup: typeof import('bootstrap-vue-next')['BFormRadioGroup']
    BModal: typeof import('bootstrap-vue-next')['BModal']
    BOffcanvas: typeof import('bootstrap-vue-next')['BOffcanvas']
    BPagination: typeof import('bootstrap-vue-next')['BPagination']
    BRow: typeof import('bootstrap-vue-next')['BRow']
    BSpinner: typeof import('bootstrap-vue-next')['BSpinner']
    BTab: typeof import('bootstrap-vue-next')['BTab']
    BTabs: typeof import('bootstrap-vue-next')['BTabs']
    ChoicesInput: typeof import('./src/components/ChoicesInput.vue')['default']
    ChoicesSelect: typeof import('./src/components/ChoicesSelect.vue')['default']
    DataTable: typeof import('./src/components/data-table.vue')['default']
    DropDown: typeof import('./src/components/DropDown.vue')['default']
    EmptyState: typeof import('./src/components/EmptyState.vue')['default']
    ExportButton: typeof import('./src/components/ExportButton.vue')['default']
    FileUpload: typeof import('./src/components/FileUpload.vue')['default']
    FileUploader: typeof import('./src/components/FileUploader.vue')['default']
    FlatPicker: typeof import('./src/components/FlatPicker.vue')['default']
    FormField: typeof import('./src/components/FormField.vue')['default']
    GridJsTable: typeof import('./src/components/GridJsTable.vue')['default']
    InputMask: typeof import('./src/components/InputMask.vue')['default']
    JsVectorMap: typeof import('./src/components/JsVectorMap.vue')['default']
    LoadingButton: typeof import('./src/components/LoadingButton.vue')['default']
    LoadingState: typeof import('./src/components/LoadingState.vue')['default']
    LogoBox: typeof import('./src/components/LogoBox.vue')['default']
    MenuItem: typeof import('./src/components/AppMenu/MenuItem.vue')['default']
    MenuItemLink: typeof import('./src/components/AppMenu/MenuItemLink.vue')['default']
    MenuItemWithChildren: typeof import('./src/components/AppMenu/MenuItemWithChildren.vue')['default']
    PageTitle: typeof import('./src/components/PageTitle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBox: typeof import('./src/components/SearchBox.vue')['default']
    TablePagination: typeof import('./src/components/TablePagination.vue')['default']
    UIComponentCard: typeof import('./src/components/UIComponentCard.vue')['default']
  }
  export interface ComponentCustomProperties {
    vBToggle: typeof import('bootstrap-vue-next')['vBToggle']
  }
}
